version: '3'

services:
  pegasusweb:
    
    image: pegasusweb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"    
networks:
  default:
    external:
      name: nat